package be.vives.vivesplus.enum

enum class DashboardType {
    WEATHER, NEXTCOURSETODAY, LATERCOURSETODAY, DAYDELIMITER, MESSAGE, CANCELLEDCOURSE, NEXTCOURSELATER, CURRENTCOURSE, CATERING, BUS, TRAIN, EVENT, ALLDAYEVENT, PARKING
}